server:
  error:
    include-stacktrace: on_param

########## MARIADB CONFIGURATION ###########
spring:
  application:
    name: springboot-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/anime_db?useTimezone=true&createDatabaseIfNotExist=true
    username: root
    password: Paulo1313
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

########## SPRING ACTUATOR ###########
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus